### PR TITLE
Enhancement: Specify environment variable in env section of Travis configuration

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] specifies an environment variable in the `env` section because that's it what it's used for

### CODE REVIEW

**Comment by 0x20h** [comment]
:+1:, thanks.

**Comment by localheinz** [comment]
@gfosco 

Waiting for you to merge #229 before I'm rebasing this one!

**Comment by localheinz** [comment]
@gfosco 

Rebased!

**Comment by gfosco** [comment]
:+1:

**Pull request merged**
