### PR TITLE
626 no null values in cookie

### PR DESCRIPTION
**Pull request by JorisVanEijden**
Both JsonWireProtocol and w3c protocol say to leave an entry off
rather than having a null value.

https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol
https://w3c.github.io/webdriver/#add-cookie

### CODE REVIEW

**Comment by JorisVanEijden** [comment]
The travis fail seems to be unrelated to this PR:
```bash
1) Facebook\WebDriver\WebDriverTimeoutsTest::testShouldFailGettingDelayedElementWithoutWait
Failed asserting that exception of type "Facebook\WebDriver\Exception\NoSuchElementException" is 
thrown.
```
How does this happen? And what can I do to fix it?

The code coverage decreased even though every single line I touched is tested and I added an extra test. How does this happen? And what can I do to fix it?

**Comment by derekmd** [comment]
With Chromedriver 74 binaries released, it now causes some cookie requests to fail without this pull request being merged and tagged.

https://chromium-review.googlesource.com/c/chromium/src/+/1366925/3/chrome/test/chromedriver/window_commands.cc#1564

As a workaround, you must manually set every cookie value to avoid `null` Set-Cookie items being sent.

**Comment by OndraM** [comment]
Thanks @JorisVanEijden for the catch. I rebased the branch against current community branch, let's see if the Travis build now pass. If so, I will get it merged.

**Comment by OndraM** [comment]
Merged, thanks @JorisVanEijden! :100:

**Pull request merged**
