### PR TITLE
Fix: const overwritten

### PR DESCRIPTION
**Pull request by danielemontesi**
Fix: const overwritten

### CODE REVIEW

**Comment by danielemontesi** [comment]
@OndraM, please could you help me ? Why Travis builds are pending ? Thank you in advance

**Comment by OndraM** [comment]
@danielemontesi Sorry, the Travis build were probably just a bit delayed because of queue on Travis side. Look they then passed.

Thanks for you contribution! And could you please squash all your commits into just one? Then it will look good to merge.

**Comment by OndraM** [comment]
@danielemontesi Ping :)?

**Comment by OndraM** [comment]
Squashed and merged manually, thanks @danielemontesi!

**Pull request closed without merging**
