### PR TITLE
Pull request for #212

### PR DESCRIPTION
**Pull request by janoszen**
Pull request as per @gfosco via #212

### CODE REVIEW

**Comment by gfosco** [comment]
Looks like great progress..  Can you rebase to fix the merge conflict?

**Comment by janoszen** [comment]
Sorry for the delay guys, conflict should be fixed.

**Comment by gfosco** [comment]
I'll give this a day to see if anyone has issues or comments... Otherwise, how about we make this v1.0.0?

**Comment by 0x20h** [comment]
+1 for v1.0.0

Comments&Feedback would be very welcome!

**Comment by php-denken** [comment]
+1

**Comment by janoszen** [comment]
@gfosco day's over... how about pushing the button before more changes creep in?

**Comment by gfosco** [comment]
Ok!  tagged 1.0.0 and updated packagist.  Thanks!  What's next? :)

**Comment by janoszen** [comment]
Not sure. Writing better docs? With examples maybe?

**Pull request merged**
