### PR TITLE
PSR-2 codestyle

### PR DESCRIPTION
**Pull request by OndraM**
Hi, as was discussed in #212 and #190, I've finally adjusted the codestyle to match PSR-2. 
This can eg. allow simpler contributing, as PSR-2 is currently standard in most modern PHP libraries.

I've added also some useful checks on top of PSR-2 based on Symfony codestyle.

Last but not least I've added the codestyle checks to the Travis build.

What do you think? All code should be backwards compatible, the changes are only in the codestyle.

### CODE REVIEW

**Comment by gfosco** [comment]
👍  It looks pretty good to me... I'll wait a couple days if anyone else wants to comment, then look to merge.

**Comment by OndraM** [comment]
So how does it look :-)? I started work on #244 , but would be great to have this merged first to avoid conflicts.

**Comment by gfosco** [comment]
💥  🎆  🍻

**Comment by gfosco** [comment]
tagged 1.1.3

**Pull request merged**
