### PR TITLE
PHPDoc: WebDriverElement::getAttribute may return null

### PR DESCRIPTION
**Pull request by dunglas**
Just a tiny docblock fix.

### CODE REVIEW

**Comment by OndraM** [comment]
Hi @dunglas , this PR is targeted to master branch, which - despite its name - is no longer maintained and freezed. The community development is now in `community` branch. 

Could you please rebase the PR and edit it then to target this branch?

Thanks a lot :+1:

**Comment by dunglas** [comment]
@OndraM, sorry. Fixed.

**Comment by OndraM** [comment]
Merged, thanks @dunglas :+1: . These kind of fixes will help as with transition to PHP7 strict typehints in (hopefully) near future :).

If you will came across something similar in php-webdriver codebase, PR will be appreciated :)!

**Comment by dunglas** [comment]
I'll do.

You may also try my tiny tools that automatically convert docblocks to typehints: https://github.com/dunglas/phpdoc-to-typehint

If tests pass, perfect, if they fail, you know which Docblocks to fix.

**Pull request merged**
