### PR TITLE
Exception classes

### PR DESCRIPTION
**Pull request by bertramakers**
Combination of PR #205 and #181.

### CODE REVIEW

**Comment by whhone** [comment]
I am sorry @bertramakers . I am not working on this project anymore.

**Comment by bertramakers** [comment]
Then who is? No one?

**Comment by chhumphries-ebay** [comment]
Can this please get merged?

**Comment by sogub** [comment]
Thank you! This solves the issue for me.

One for me, these files are missing require_once() calls in __init__.php:
- lib/exceptions/UnexpectedTagNameWebDriverException.php
- lib/exceptions/UnrecognizedExceptionWebDriverException.php
- lib/exceptions/UnsupportedOperationWebDriverException.php

**Comment by sogub** [comment]
Is this project still maintained?

**Comment by gabrielpreston** [comment]
As best as I can tell this project has been abandoned. I'm not sure anyone's forked it and started to maintain it yet.

**Comment by onno-vos-dev** [comment]
I can fork this, give me a week or so to merge some outstanding PR's and issues. :) 

I started working on a fork a month or so back but never really got it done.

**Comment by sogub** [comment]
Awesome! I can help work on it once forked.

**Comment by bertramakers** [comment]
Yeah this seems abandoned, even though they said otherwise on the FB group of this project.

If you're gonna fork it, I'd suggest to actually use namespaces and reformat the code to use the PSR-4 coding standards. This was not done in this project because they followed the FB guidelines instead which has its own coding standards and apparently forbids to use namespaces(?).

So this PR was just an attempt to fix class name conflicts without using namespaces. But if you would use namespaces you don't need this PR.

**Comment by onno-vos-dev** [comment]
@bertramakers: That's exactly what I was doing earlier. I never understood this coding standard anyway. I'm aiming for next Sunday :)

**Comment by bertramakers** [comment]
Great! I hope we can get some kind of traction with your fork, as by now I think quite a lot of people have forked this project tho fix issues like this and/or add namespacing. So it would be nice if we could get all those people to work on a single fork, instead of having 20 variations of the same library, some of which are probably no longer maintained by now anyway.

I'm not actively using php-webdriver in a project right now myself, but I might help out a bit whenever I have some time and I see that there's an open issue.

I don't have much experience with this project, but I do have quite some experience with the PHPUnit webdriver library and I stumbled upon this project while looking for something more losely-coupled.

**Comment by jameshd** [comment]
I also have a fork and am actively using it in projects. Please do give me a nudge if there becomes a new master repo so to speak!

**Comment by whhone** [comment]
I have forwarded this thread to my previous teammates in case they didn't notice the discussion here. I would wait for a while for their replies before deciding to fork the project.

If nobody is going to maintain it, I would say, let's fork it.

**Comment by gabrielpreston** [comment]
I'm almost of the opinion we should fork this anyways because most people seem to want name spacing and PSR compliant code.

**Comment by whhone** [comment]
I have talked with them and I don't think there will be someone to manage this project in the near future.

**Comment by sogub** [comment]
Ok. Time to fork()!

**Comment by onno-vos-dev** [comment]
Ok cool! I'll get to work! @jameshd I'll get in touch with you during the week! :)

**Comment by sogub** [comment]
thanks onno-vos-dev!

**Comment by gfosco** [comment]
Hi everyone.  I've picked up maintaining this project at Facebook for now, and I'm very open to including your contributions.  Will be spending some time getting up to speed and if any of you want to talk about it, please email me at fjm@fb.com

**Comment by onnovos** [comment]
@gfosco Please don't take this the wrong way but I am a bit confused. On facebook at first it was said that someone was going to take over, then nobody showed up here and @whhone confirmed that "I don't think there will be someone to manage this project in the near future".

I would be very happy to see Facebook continuing to support this project and be open to discuss the possibility of implementing Namespacing and PSR standard formatting. It's something that many of us has been struggling with but it kept getting rejected due to FB internal coding standards. (Which even though I can respect them, for an open source project you might have to re-consider).

I think I can speak for a lot of us out here, that we just want some clarity on the support from FB for this project.

**Comment by gfosco** [comment]
I understand totally.  I support Namespacing, and PSR-2 (and more)... You can take a look at facebook/facebook-php-sdk-v4 and see a more compliant project that I built and have been managing (the master branch is going to be 5.0 and is almost entirely refactored by the community.)

For now, you've got me... so lets make some good stuff happen.

**Comment by bertramakers** [comment]
I completely agree. I'd love for this project to be officially supported by Facebook, but at this point there has been a lot of confusion about whether or not that's going to be the case moving forward, and there seems to be a lot of demand for either a fork or a new major version of this library that uses namespaces and is PSR compliant, instead of working our way around the limitations of non-namespaced classes like I did in this PR (because I already knew namespaces were out of the question under the current guidelines).

Especially because in this case those guidelines clearly cause conflicts when working with other libraries, which is why these PRs and issues were created in the first place.

But to be honest I'm happy that we're now at least discussing this, as this PR has been open for some time and I had given up hope that this project would still be maintained in any form.

**Comment by bertramakers** [comment]
Ah our posts seem to have crossed. Great to hear!

**Comment by onnovos** [comment]
@gfosco Cool! I'll finish up my fork then including namespaces and PSR compliant formatting. Should be ready by the end of this week.

**Comment by whhone** [comment]
@gfosco Awesome! Glad to hear from the new maintainer! :D

**Comment by gfosco** [comment]
Closing this.. When something is ready, open a PR against the community branch (unless things change in #212 )  Thanks!

**Pull request closed without merging**
