### PR TITLE
add @access to docblocks

### PR DESCRIPTION
**Pull request by Tjoosten**
Add `@access` attribute to the docblocks

### CODE REVIEW

**Comment by gfosco** [comment]
I'd allow adding the ~7 `@access private` lines, but the public ones seem superfluous.  If you want to update your PR with just that, I'll merge it.

**Comment by Tjoosten** [comment]
How u mean srry not good at English

**Comment by gfosco** [comment]
There are 7 places where you add:

```
@access private
```

I will allow adding those.  

Please remove all instances of `@access public`

**Comment by Tjoosten** [comment]
so all the `@access public` needed to be removed?

**Comment by gfosco** [comment]
Yeah, seems like it has no function.

**Comment by 0x20h** [comment]
Is `@access` necessary for PHP `>=5.3` anyway?
Seems a bit redundant.

**Comment by gfosco** [comment]
True... Let's close this.

**Pull request closed without merging**
