### PR TITLE
Allow Symfony4 components

### PR DESCRIPTION
**Pull request by VolCh**
Symfony4 is in beta now and I think that it's time to allow developers test theirs projects with new set of components. But php-webdriver blocks install some of its. This PR allow.

### CODE REVIEW

**Comment by OndraM** [comment]
Hi @VolCh, thank you very much and thanks for your first contribution to php-webdriver :).

It looks like `ProcessBuilder()` we use is about to be removed in Symfony 4 (https://github.com/symfony/process/blob/master/CHANGELOG.md#400), so we have to update the code first - it won't work with Symfony 4. (Moreover, looks like we don't have this covered by unit tests 😬)

I may have a time to look at this during week, but if you are interested in making the code compatible with Symfony 4, it will be very much appreciated :). (But keep on mind it should be compatible also with previous Symfony versions - so I'm afraid there will have be some compatibility if condition...)

**Comment by OndraM** [comment]
(I also changed minimum-stability to beta in composer.json, so the beta version gets installed with `composer update`).

**Comment by OndraM** [comment]
Also, https://github.com/FriendsOfPHP/PHP-CS-Fixer depends on symfony/process, and version with Symfony 4 support is not yet tagged (though it is already merged), so I'm afraid we will have to wait for its release few days (otherwise Symfony 4 beta won't install, and you will get the 3.4 version at most).

**Comment by VolCh** [comment]
Hi @OndraM 

I changed PR  status to WIP until support of 4.0 in phpunit (also merged in 5.7 branch) and php-cs-fixer not tagged. Now all symfony components is 4.0.0-BETA1. 

Also introduced BC check for <4.0 by `class_exists('ProcessBuilder')`, but in 3.4 it will trigger deprecated message. In fact we can use `new Process()` instead of `ProcessBuilder` without lot of boilerplate code starting from 3.3, but I not found any non-ugly way to detect version of Process Component, especially in the case of 3.4 version.

**Comment by OndraM** [comment]
@VolCh Great job! And I will soon append tests to make sure the ChromeDriver service works as expected. And lets hope the dependencies will get tagged soon, so we can merge this :).

**Comment by VolCh** [comment]
I rebased branch but saucelabs tests failed when local passed. I have no idea why.

**Comment by OndraM** [comment]
@VolCh Looks like the tests met build in some other branch and failed on Saucelabs concurrency limit. I've restarted them, sorry about that :)

**Comment by VolCh** [comment]
The tests are passed. Thank you @OndraM!

Now we have three ways:
1. Merge as is (a very ugly way for my mind) and clear after vendors released  with Symfony 4 supports.
2. Wait for vendor's releases and only then merge with clear composer.json
3. Clear composer.json now, merge it in the main branch and vendors  will be installed automatically  when they are released

**Comment by OndraM** [comment]
@VolCh Nicely done, thank you :-).

As for the next steps - looks like the packages we are talking about have frequent releases, so I suggest we can wait those few days until phpunit and php-cs-fixer tags their next releases, and make a php-webdriver release afterward.

**Comment by VolCh** [comment]
Deprecated message with symfony-process:3.4 not trows now.

**Comment by OndraM** [comment]
@VolCh New PHPUnit 5.7 was tagged, if you please update the composer.json, I'll be glad to merge this 💪 .

**Comment by VolCh** [comment]
@OndraM thanks for PHPUnit tag :)

I reverted use PHPUnit dev branch.

**Comment by OndraM** [comment]
Merged and everything is being updated by Composer just fine 🎉 .

```
$ composer update
...
Package operations: 0 installs, 11 updates, 0 removals
  - Updating symfony/process (v3.3.12 => v4.0.0-BETA4): Downloading (100%)         
  - Updating symfony/debug (v3.3.12 => v4.0.0-BETA4): Downloading (100%)         
  - Updating symfony/console (v3.3.12 => v4.0.0-BETA4): Downloading (100%)         
  - Updating symfony/event-dispatcher (v3.3.12 => v4.0.0-BETA4): Downloading (100%)         
  - Updating symfony/finder (v3.3.12 => v4.0.0-BETA4): Downloading (100%)         
  - Updating symfony/options-resolver (v3.3.12 => v4.0.0-BETA4): Downloading (100%)         
  - Updating symfony/stopwatch (v3.3.12 => v4.0.0-BETA4): Downloading (100%)         
  - Updating symfony/yaml (v3.3.12 => v4.0.0-BETA4): Downloading (100%)         
  - Updating symfony/var-dumper (v3.3.12 => v4.0.0-BETA4): Downloading (100%)         
  - Updating symfony/filesystem (v3.3.12 => v4.0.0-BETA4): Downloading (100%)         
  - Updating symfony/config (v3.3.12 => v4.0.0-BETA4): Downloading (100%) 
```

@VolCh Great job! 💯

**Comment by OndraM** [comment]
🎉 php-webdriver 1.5.0 was just tagged

**Pull request merged**
