### PR TITLE
Small Typo in isJavascriptEnabled

### PR DESCRIPTION
**Pull request by reense**

### CODE REVIEW

**Comment by OndraM** [comment]
@reense Thanks for the PR! However the typo is obviously also in tests, which needs to be fixed as well (see the failed travis build).

**Comment by OndraM** [comment]
Ping @reense :)?

**Comment by reense** [comment]
Hi @OndraM , This is new for me. I'll dive in to it tomorrow 👍

**Comment by OndraM** [comment]
@reense 👍  Great, looking forward :-). Thanks!

**Comment by OndraM** [comment]
@reense ping :)?

**Comment by reense** [comment]
@OndraM  Oh shit, sorry I forgot! :( Busy with work, will do it as soon as I can!

**Comment by OndraM** [comment]
@reense Rebased & merged. Thanks :)

**Pull request merged**
